lis_extender/bags/urls.py
from django.urls import path
from .views import LpuDetail, BagLPUDetail, BagLPUCreate, ScanBagView, AddBagtoLPU, BagsReportView, BagsLpuList, \
    LpuList, ScannedBagList, return_barcode, BagLPUUpdate, ScanBagDelete

urlpatterns = [
    path('bag_reg/', ScannedBagList.as_view(), name='scanbag_list'),
    path('bag_reg/add/', ScanBagView.as_view(), name='scan_bag'),
    path('bag_reg/<int:pk>/delete/', ScanBagDelete.as_view(), name='scanbag_delete'),
    path('lpu/', LpuList.as_view(), name='lpu_bags_list'),
    path('lpu/<int:pk>/', LpuDetail.as_view(), name='lpu'),
    path('lpu/<int:pk>/add_barcode/', AddBagtoLPU.as_view(), name='add_bag_to_lpu'),
    path('bag_lpu/', BagsLpuList.as_view(), name='bag_lpu_list'),
    path('bag_lpu/<int:pk>/', BagLPUDetail.as_view(), name='bag_lpu'),
    path('bag_lpu/<int:pk>/barcode.pdf', return_barcode, name='bag_lpu_barcode'),
    path('bag_lpu/add/', BagLPUCreate.as_view(), name='add_baglpu'),
    path('bag_lpu/<int:pk>/edit/', BagLPUUpdate.as_view(), name='bag_lpu_edit'),
    path('report/', BagsReportView.as_view(), name='bags_report'),
]

lis_extender/lis_extender/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('finance/', include('finance.urls')),
    path('bags/', include('bags.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('catalog/', include('analyzes.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lis_extender/bags/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from mainapp.models import LogEvent
from django.utils import timezone

DATETIME_INPUT_FORMATS = settings.DATETIME_INPUT_FORMATS


class LPU(models.Model):
    id = models.CharField(primary_key=True, max_length=100)
    code = models.CharField(max_length=20, unique=True)
    name = models.TextField()
    is_active = models.BooleanField()

    def __str__(self):
        return f'{self.code} {self.name}'

    def get_absolute_url(self):
        return reverse('lpu', kwargs={"pk": self.pk})

    def get_finance_url(self):
        return reverse('Customer details', kwargs={'pk': self.pk})

    def get_add_bag_url(self):
        return reverse('add_bag_to_lpu', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('code',)


class BagLPU(models.Model):
    barcode = models.IntegerField(unique=True)
    lpu = models.ForeignKey(to=LPU, on_delete=models.SET_NULL, blank=True, null=True, related_name='bag',
                            related_query_name='bags')
    create_date = models.DateTimeField(default=timezone.now)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, blank=True, null=True, default=None,
                                related_name='creator')

    def __str__(self):
        return f'ШК: {self.barcode} ЛПУ: {self.lpu}'

    def get_absolute_url(self):
        return reverse('bag_lpu', kwargs={'pk': self.pk})

    def get_edit_url(self):
        return reverse('bag_lpu_edit', kwargs={'pk': self.pk})

    def get_barcode_url(self):
        return reverse('bag_lpu_barcode', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('barcode',)


class ScannedBag(models.Model):
    barcode = models.IntegerField()
    scan_date = models.DateTimeField(default=timezone.now)
    lpu = models.ForeignKey(to=BagLPU, on_delete=models.CASCADE)
    incoming = models.BooleanField(default=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, blank=True, null=True, default=None)

    def __str__(self):
        formatted_scan_date = self.scan_date.strftime(DATETIME_INPUT_FORMATS[0])
        return f'{self.barcode} {formatted_scan_date} {self.lpu.lpu}'

    def get_absolute_url(self):
        return reverse('scanbag_delete', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('scanbag_delete', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('-scan_date',)


class PermissionReport(models.Model):
    name = models.CharField(max_length=2)


class BagLPULog(models.Model):
    obj_instance = models.ForeignKey(to=BagLPU, on_delete=models.CASCADE)
    event = models.ForeignKey(to=LogEvent, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-event__timestamp',)

lis_extender/bags/forms.py
from datetime import datetime, timedelta

from django.conf import settings
from django import forms
from .models import LPU, BagLPU

DATE_INPUT_FORMATS = settings.DATE_INPUT_FORMATS


class ScannedBagForm(forms.Form):
    barcode = forms.IntegerField(required=True, label='Штрих-код сумки',
                                 widget=forms.NumberInput(attrs={'class': 'uk-input',
                                                                 'autocomplete': 'off'}))

    def clean(self):
        form_data = self.cleaned_data
        barcode = form_data['barcode']
        try:
            bag = BagLPU.objects.get(barcode=barcode)
            hour_ago = datetime.now() - timedelta(hours=1)
            if bag.scannedbag_set.filter(scan_date__gt=hour_ago).exists():
                self.add_error('barcode', f'Контейнер {barcode} был сканирован менее часа назад!')
        except BagLPU.DoesNotExist:
            self.add_error('barcode', f'Контейнер {barcode} не привязан к ЛПУ!')


class BagLpuForm(forms.Form):
    autogenerate_barcode = forms.BooleanField(label='Сгенерировать код сумки', initial=True, required=False,
                                              widget=forms.CheckboxInput(attrs={'class': 'uk-checkbox'}))
    barcode = forms.IntegerField(label="Штрих-код сумки", required=False,
                                 widget=forms.NumberInput(attrs={'class': 'uk-input',
                                                                 'autocomplete': 'off'}))
    lpu = forms.ModelChoiceField(required='True', label="ЛПУ",
                                 queryset=LPU.objects.all(), widget=forms.Select(
            attrs={'class': 'js-select-search'}))

    def clean(self):
        form_data = self.cleaned_data
        barcode = form_data['barcode']
        try:
            bag = BagLPU.objects.get(barcode=barcode)
            self.add_error('barcode', f'Контейнер с штрих-кодом {barcode} уже привязан к ЛПУ {bag.lpu}.')
        except BagLPU.DoesNotExist:
            pass


class BagLpuEdit(forms.ModelForm):
    barcode = forms.IntegerField(required=True, label="Штрих-код сумки",
                                 widget=forms.NumberInput(attrs={'class': 'uk-input',
                                                                 'autocomplete': 'off'}))
    lpu = forms.ModelChoiceField(required='True', label="ЛПУ",
                                 queryset=LPU.objects.all(), widget=forms.Select(
            attrs={'class': 'js-select-search'}))

    class Meta:
        model = BagLPU
        fields = [
            'barcode',
            'lpu'
        ]


class BagLpuAdd(forms.Form):
    autogenerate_barcode = forms.BooleanField(label='Сгенерировать код сумки', initial=True, required=False,
                                              widget=forms.CheckboxInput(attrs={'class': 'uk-checkbox'}))
    barcode = forms.IntegerField(label="Штрих-код сумки", required=False,
                                 widget=forms.NumberInput(attrs={'class': 'uk-input',
                                                                 'autocomplete': 'off'}))


class BagsReportForm(forms.Form):
    lpu = forms.ModelMultipleChoiceField(required=True, label='ЛПУ',
                                         queryset=LPU.objects.all(), widget=forms.SelectMultiple(
            attrs={'class': 'js-select-search',
                   }))
    start_date = forms.DateField(required=True, label='Начало периода',
                                 input_formats=DATE_INPUT_FORMATS,
                                 widget=forms.DateInput(attrs={'class': 'uk-input datepicker-here',
                                                               }))
    end_date = forms.DateField(required=True, label='Конец периода',
                               input_formats=DATE_INPUT_FORMATS,
                               widget=forms.DateInput(attrs={'class': 'uk-input datepicker-here',
                                                             }))

lis_extender/bags/views.py
from io import BytesIO

from django.contrib import messages
from django.db.models import Max
from django.http import HttpResponse
from django.shortcuts import redirect, reverse
from django.views.generic import DetailView, FormView, UpdateView
from django.contrib.auth.mixins import PermissionRequiredMixin
from reportlab.graphics.barcode import code128
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

from .filters import BagLpuFilter, LpuFilter, ScannedBagsFilter
from .forms import ScannedBagForm, BagLpuForm, BagLpuAdd, BagsReportForm, BagLpuEdit
from .models import ScannedBag, LPU, BagLPU, BagLPULog
from mainapp.views import ChangeLogMixin, FilteredListView, AjaxDeleteView


class ScanBagView(PermissionRequiredMixin, FormView):
    form_class = ScannedBagForm
    template_name = 'bags/scan_form.html'
    permission_required = 'bags.add_scannedbag'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['object_list'] = ScannedBag.objects.all()[:10]
        return context

    def form_valid(self, form):
        barcode = form.cleaned_data.get('barcode')
        lpu = BagLPU.objects.get(barcode=barcode)
        ScannedBag.objects.create(barcode=barcode, lpu=lpu, creator=self.request.user)
        return redirect(reverse('scan_bag'))


class ScanBagDelete(PermissionRequiredMixin, AjaxDeleteView):
    model = ScannedBag
    permission_required = 'bags.delete_scannedbag'


class LpuDetail(PermissionRequiredMixin, DetailView):
    model = LPU
    permission_required = 'bags.view_lpu'


class BagLPUDetail(PermissionRequiredMixin, DetailView):
    template_name = 'bags/bag_lpu_detail.html'
    model = BagLPU
    permission_required = 'bags.view_baglpu'


class BagLPUUpdate(PermissionRequiredMixin, UpdateView, ChangeLogMixin):
    model = BagLPU
    form_class = BagLpuEdit
    template_name = "bags/bag_lpu_update.html"
    queryset = BagLPU.objects.all()
    permission_required = 'bags.change_baglpu'
    log_connector_class = BagLPULog

    def form_valid(self, form):
        form_data = form.cleaned_data
        barcode = form_data.get('barcode')
        lpu = form_data.get('lpu')
        bag_lpu = self.object
        orig_object = BagLPU.objects.get(pk=self.kwargs.get('pk'))
        if orig_object.barcode == barcode and orig_object.lpu == lpu:
            messages.info(self.request, 'Изменений нет')
            return redirect(bag_lpu)
        else:
            self.make_log(attribs=form_data.keys(), original_object=orig_object)
            messages.success(self.request, 'Данные по контейнеру обновлены.')
            super().form_valid(form)
            return redirect(bag_lpu)


class BagLPUCreate(PermissionRequiredMixin, FormView):
    form_class = BagLpuForm
    success_url = "/bags/bag_lpu/"
    template_name = "bags/bag_lpu_add.html"
    lpu = ''
    permission_required = 'bags.add_baglpu'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        if pk:
            self.lpu = LPU.objects.get(pk=pk)
        context['lpu'] = self.lpu
        return context

    def form_valid(self, form, **kwargs):
        pk = self.kwargs.get('pk')
        barcodes = BagLPU.objects.all()
        if form.cleaned_data.get('autogenerate_barcode'):
            barcode = str(int(barcodes.aggregate(Max('barcode')).get('barcode__max')) + 1)
        else:
            barcode = form.cleaned_data['barcode']
        if pk:
            lpu = LPU.objects.get(pk=pk)
        else:
            lpu = form.cleaned_data['lpu']
        creator = self.request.user
        bag_lpu = BagLPU(barcode=barcode, lpu=lpu, creator=creator)
        bag_lpu.save()
        messages.success(self.request, f'Контейнер с штрих-кодом {barcode} успешно добавлен к ЛПУ {lpu}.')
        return redirect(bag_lpu)


class AddBagtoLPU(BagLPUCreate):
    form_class = BagLpuAdd
    template_name = 'bags/bag_lpu_add.html'


class BagsReportView(PermissionRequiredMixin, FormView):
    template_name = "bags/report_form.html"
    form_class = BagsReportForm
    permission_required = 'bags.view_permissionreport'

    def form_valid(self, form, **kwargs):
        context = super().get_context_data(**kwargs)
        result = []
        cleaned_data = form.cleaned_data
        lpus = cleaned_data['lpu']
        start_date = cleaned_data['start_date']
        end_date = cleaned_data['end_date']
        for lpu in lpus:
            bags_lpus = BagLPU.objects.filter(lpu=lpu)
            if len(bags_lpus) > 0:
                bags_dict = {'lpu': str(lpu), 'data': []}
                for bags_lpu in bags_lpus:
                    filtered_bags = ScannedBag.objects.filter(lpu=bags_lpu, scan_date__range=(start_date, end_date))
                    detail = {}
                    detail['count'] = len(filtered_bags)
                    detail['scanned_bags'] = filtered_bags
                    bags_dict['data'].append({'barcode': bags_lpu.barcode, 'detail': detail})
                result.append(bags_dict)
        context['report'] = result
        context['start_date'] = start_date
        context['end_date'] = end_date
        return self.render_to_response(context)


class BagsLpuList(PermissionRequiredMixin, FilteredListView):
    queryset = BagLPU.objects.all()
    template_name = 'bags/bag_lpu_list.html'
    paginate_by = 25
    filterset_class = BagLpuFilter
    permission_required = 'bags.view_baglpu'


class LpuList(PermissionRequiredMixin, FilteredListView):
    queryset = LPU.objects.all()
    template_name = 'bags/lpu_list.html'
    paginate_by = 25
    filterset_class = LpuFilter
    permission_required = 'bags.view_lpu'


class ScannedBagList(PermissionRequiredMixin, FilteredListView):
    queryset = ScannedBag.objects.select_related('lpu__lpu').all()
    template_name = 'bags/scanned_list.html'
    paginate_by = 15
    filterset_class = ScannedBagsFilter
    permission_required = 'bags.view_scannedbag'


def generate_barcode_pdf(barcode, lpu_code):
    pdfmetrics.registerFont(TTFont('Vera', 'Vera.ttf'))
    pdf_file = BytesIO()
    pdf_file.seek(0)
    lpu_code = lpu_code
    c = canvas.Canvas(pdf_file, pagesize=(44 * mm, 25 * mm))
    barcode = code128.Code128Auto(barcode, barWidth=0.4 * mm, barHeight=12 * mm, humanReadable=1)
    barcode.drawOn(c, 1 * mm, 5 * mm)
    t = c.beginText()
    t.setFont('Vera', 6)
    t.setTextOrigin(1 * mm, 20 * mm)
    t.textLine(lpu_code)
    c.drawText(t)
    c.showPage()
    c.save()
    return pdf_file


def return_barcode(request, pk):
    if request.method == 'GET':
        BL = BagLPU.objects.get(pk=pk)
        barcode = BL.barcode
        lpu_code = BL.lpu.name
        buffer = generate_barcode_pdf(barcode, lpu_code)
        response = HttpResponse(buffer.getvalue(), content_type='application/pdf')
        response['Content-Disposition'] = f'filename=barcode.pdf'
        return response

lis_extender/bags/templates/bags/bag_lpu_add.html
{% extends "bags/base_create_form.html" %}

{% block title %}
Выдать контейнер ЛПУ {{ lpu }} |
{% endblock title%}

{% block form_title %}
Выдать контейнер ЛПУ {{ lpu }}
{% endblock form_title %}


{% block scripts %}
<script>
let needAutogen = document.querySelector('#id_autogenerate_barcode');
let barcodeInput = document.querySelector('#id_barcode');
let barLabel = barcodeInput.parentElement.previousElementSibling;
barLabel.hidden = true;
barcodeInput.hidden = true;
needAutogen.addEventListener('change', function(){
if(needAutogen.checked){
    barLabel.hidden = true;
    barcodeInput.hidden = true;
} else {
    barLabel.hidden = false;
    barcodeInput.hidden = false;
    setCaretPosition('id_barcode', 0);
}
});
</script>
<script>
document.addEventListener('keydown', function(event){
if(event.code == 'Tab'){
    event.preventDefault();
}
});
</script>
{% endblock scripts %}

lis_extender/bags/templates/bags/bag_lpu_detail.html
{% extends "bags/base.html" %}

{% block title %}
Сумка {{baglpu.barcode}} |
{% endblock title%}

{% block header %}
Сумка {{baglpu.barcode}}
{% endblock header %}

{% block main %}
<div class="container">
    <div class="uk-grid-large" uk-grid>
        <div class="uk-width-auto">
            <div>
            {% if perms.bags.change_baglpu %}
                <a title="Редактировать" href="{{ object.get_edit_url }}" class="uk-icon-button uk-icon uk-margin-small-right button-nav" uk-icon="pencil"></a>
            {% endif %}
                <a title="Печать" target="_blank" href="{{ object.get_barcode_url }}" class="uk-icon-button uk-icon button-secondary" uk-icon="print"></a>
            </div>
        </div>
        <div class="uk-width-expand uk-first-column">
            <h2 class="uk-heading-divider">{{object}}</h2>
        </div>
    </div>
</div>
<div class="uk-grid-large uk-child-width-1-2 uk-margin-medium-top" uk-grid>
    <div>
        <div class="uk-card-default uk-card-body">
            <table class="uk-table uk-table-divider uk-table-middle">
                <tbody>
                <tr>
                    <th>Штрих-код сумки</th>
                    <td>{{baglpu.barcode}}</td>
                </tr>
                <tr>
                    <th>Привязана к ЛПУ</th>
                    <td><a class="uk-link-reset" href="{{baglpu.lpu.get_absolute_url}}">{{baglpu.lpu}}</a></td>
                </tr>
                <tr>
                    <th>Кем создана</th>
                    {% if baglpu.creator == None %}
                    <td>Нет данных</td>
                    {% else %}
                    <td>{{baglpu.creator.first_name}} {{baglpu.creator.last_name}}</td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Когда создана</th>
                    {% if baglpu.create_date == None %}
                    <td>Нет данных</td>
                    {% else %}
                    <td>{{baglpu.create_date|date:'d.m.Y H:i'}}</td>
                    {% endif %}
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    {% if perms.bags.view_scannedbag %}
    <div>
    <div class="uk-card-default uk-card-body">
        <table class="uk-table uk-table-divider uk-table-middle">
            <thead class="uk-background-secondary">
            <tr>
                <th scope="col">Время сканирования <small>(10 последних)</small></th>
                {% if perms.bags.delete_scannedbag %}
                <th></th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for scanned in baglpu.scannedbag_set.all|slice:":10" %}
            <tr id="row_{{ forloop.counter }}">
                <td>{{scanned.scan_date|date:'d.m.Y H:i'}}</td>
                {% if perms.bags.delete_scannedbag %}
                <td>
                     <a class="uk-icon-button uk-icon" uk-icon="icon: trash" title="Удалить" href="#modal_{{forloop.counter}}" uk-toggle></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    </div>
    {% endif %}
</div>
<div class="uk-content uk-margin-large-top">
        <table class="uk-table uk-table-divider uk-table-middle">
            <thead class="uk-background-secondary">
            <tr>
                <th scope="col">Время изменения</th>
                <th scope="col">Кто изменил</th>
                <th scope="col">Предыдущий штрих-код</th>
                <th scope="col">Предыдущее ЛПУ</th>
            </tr>
            <tbody id="list">
            {% for event in object.baglpulog_set.all %}

            <tr>
                <td>{{event.event.timestamp|date:'d.m.Y H:i'}}</td>
                {% with log=event.event.get_data %}
                <td>{{log.author}}</td>
                <td>{{log.barcode}}</td>
                <td>{{log.lpu}}</td>
                {% endwith %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
</div>

{% if perms.mainapp.delete_scannedbag %}
{% for scanned in baglpu.scannedbag_set.all|slice:":10" %}
<div id="modal_{{forloop.counter}}" uk-modal>
    <div class="uk-modal-dialog uk-modal-body">
        <h2 class="uk-modal-title">Удаление</h2>
        <p>Вы уверены, что хотите удалить <b>{{scanned}}?</b></p>
        <p class="uk-text-right">
            <button class="uk-button uk-button-default uk-modal-close" type="button">Отмена</button>
            <a href="{{ scanned.get_delete_url }}" class="uk-button uk-button-danger delete-button"
               type="button">Удалить</a>
        </p>
    </div>
</div>
{% endfor %}
{% endif %}
{% csrf_token %}
{% endblock main %}

lis_extender/bags/templates/bags/bag_lpu_list.html
{% extends "bags/base.html" %}

{% block title %}
Список сумок | 
{% endblock title%}

{% block main %}
<table class="uk-table uk-table-divider uk-table-middle">
    <thead class="uk-background-secondary">
    <tr>
        <th class="uk-table-shrink">Штрих-код</th>
        <th class="uk-table-expand">ЛПУ</th>
        {% if perms.bags.change_baglpu %}
        <th class="uk-table-shrink">Редактировать</th>
        {% endif %}
        <th class="uk-table-shrink">Распечатать штрих-код</th>
    </tr>
    </thead>
    <tbody id="list">
{% for bag_lpu in object_list %}
<tr>
    <td><a title="Подробно" href="{{ bag_lpu.get_absolute_url }}" class="uk-link-reset">{{bag_lpu.barcode}}</a></td>
    <td><a class="uk-link-reset" href="{{bag_lpu.lpu.get_absolute_url}}">{{bag_lpu.lpu}}</a></td>
    {% if perms.bags.change_baglpu %}
    <td><a title="Редактировать" href="{{ bag_lpu.get_edit_url }}" class="uk-icon-button uk-icon button-nav" uk-icon="pencil"></a></td>
    {% endif %}
    <td><a title="Печать" target="_blank" href="{{ bag_lpu.get_barcode_url }}" class="uk-icon-button uk-icon button-secondary" uk-icon="print"></a></td>
</tr>
{% endfor %}
</tbody>
</table>
{% endblock main %}

lis_extender/bags/templates/bags/bag_lpu_update.html
{% extends "bags/base_edit_form.html" %}

{% block title %}
Редактировать контейнер {{object}} |
{% endblock title%}

{% block form_title %}
Редактировать контейнер {{ object }}
{% endblock form_title %}

lis_extender/bags/templates/bags/base.html
{% extends "mainapp/base.html" %}

{% block title %}{% endblock title %}



{% block tabs %}
    {% include "bags/tabs.html" %}
{% endblock tabs %}

{% block main %}
{% endblock main %}

{% block bottom %}
{% endblock bottom %}


{% block scripts%}
{% endblock scripts %}

lis_extender/bags/templates/bags/base_create_form.html
{% extends "mainapp/base_create_form.html" %}

{% block title %}
{% endblock title %}

{% block tabs %}
{% include "bags/tabs.html" %}
{% endblock tabs %}

{% block form_title %}
{% endblock form_title %}

{% block scripts %}
{% endblock scripts %}

lis_extender/bags/templates/bags/base_edit_form.html
{% extends "mainapp/base_edit_form.html" %}

{% block title %}
{% endblock title %}

{% block tabs %}
{% include "bags/tabs.html" %}
{% endblock tabs %}

{% block form_title %}
{% endblock form_title %}

{% block scripts %}
{% endblock scripts %}

lis_extender/bags/templates/bags/lpu_detail.html
{% extends "bags/base.html" %}

{% block title %}
ЛПУ {{lpu.code}} |
{% endblock title%}

{% block header %}
ЛПУ {{lpu.code}}
{% endblock header %}


{% block main %}
<div class="container">
    <div class="uk-grid-large" uk-grid>
        <div class="uk-width-auto">
            <div>
                {% if perms.bags.add_baglpu %}
                <a title="Добавить контейнер" href="{{ object.get_add_bag_url }}"
                   class="uk-icon-button uk-icon uk-margin-small-right button-primary" uk-icon="plus"></a>
                {% endif %}
            </div>
        </div>
        <div class="uk-width-expand uk-first-column">
            <h2 class="uk-heading-divider">{{object}}</h2>
        </div>
    </div>
</div>
<div class="uk-grid-large uk-child-width-1-2 uk-margin-medium-top" uk-grid>
    <div>
        <div class="uk-card-default uk-card-body">
            <table class="uk-table uk-table-divider uk-table-middle">
                <tbody>
                <tr>
                    <th>Код ЛПУ</th>
                    <td>{{object.code}}</td>
                </tr>
                <tr>
                    <th>Название ЛПУ</th>
                    <td>{{object.name}}</td>
                </tr>
                <tr>
                    <th>Активен</th>
                    <td>
                        {% if lpu.is_active %}
                        Да
                        {% else %}
                        Нет
                        {% endif %}
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    {% if perms.bags.view_baglpu %}
    <div>
        <div class="uk-card-default uk-card-body">
            <table class="uk-table uk-table-divider uk-table-middle">
                <thead class="uk-background-secondary">
                <tr>
                    <th scope="col">Контейнеры <span class="uk-label button-secondary">{{ object.bag.all|length }}</span></th>
                </tr>
                </thead>
                <tbody>
                {% for bag_lpu in object.bag.all %}
                <tr>
                    <td><a class="uk-link-reset" href="{{bag_lpu.get_absolute_url}}">{{bag_lpu.barcode}}</a></td>
                </tr>
                {% empty %}
                <tr>
                    <td>Нет контейнеров. {% if perms.bags.add_baglpu %}
                        <a href="{{ object.get_add_bag_url }}">Выдать новый?</a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}
</div>

{% endblock main %}

lis_extender/bags/templates/bags/lpu_list.html
{% extends "bags/base.html" %}

{% block title %}
Список ЛПУ | 
{% endblock title%}

{% block main %}
<table class="uk-table uk-table-divider uk-table-middle">
    <thead class="uk-background-secondary">
    <tr>
        <th scope="col">Код ЛПУ</th>
        <th scope="col">Название ЛПУ</th>
        <th scope="col">Активно</th>
    </tr>
    </thead>
    <tbody>
{% for lpu in object_list %}
<tr>
    <td><a class="uk-link-reset" href="{{lpu.get_absolute_url}}">{{lpu.code}}</a></td>
    <td><a class="uk-link-reset" href="{{lpu.get_absolute_url}}">{{lpu.name}}</a></td>
{% if lpu.is_active %}
    <td>Да</td>
{% else %}
    <td>Нет</td>
{% endif %}
</tr>
{% endfor %}
</tbody>
</table>
{% endblock main %}