lis_extender/analyzes/urls.py
from django.urls import path
from .views import AnalyzersListView, AnalyzerDetailView, AnalysisDetailView, AnalyzesListView, BlankDeleteView, \
    BlankDetailView, BlanksListView, BiomaterialDetailView, BiomaterialsListView, ContainerDetailView, \
    ContainersListView, BlankCreateView, BlankUpdateView, AnalyzesEditView, AnalysisMappingListView, \
    AnalysisMappingEditView, AnalysisMappingHistoryView, AnalysisMappingUpload, \
    TestEditView, Top100Analyzes, AnalyzesReportView, AnalysisHistoryView

urlpatterns = [
    path('analyzers/', AnalyzersListView.as_view(), name='Analyzers list'),
    path('analyzers/<int:pk>/', AnalyzerDetailView.as_view(), name='Analyzer'),
    path('top100/', Top100Analyzes.as_view(), name='Top100'),
    path('biomaterials/', BiomaterialsListView.as_view(), name='Biomaterials list'),
    path('biomaterials/<int:pk>/', BiomaterialDetailView.as_view(), name='Biomaterial'),
    path('containers/', ContainersListView.as_view(), name='Container list'),
    path('containers/<int:pk>/', ContainerDetailView.as_view(), name='Container'),
    path('analyzes/', AnalyzesListView.as_view(), name='Analyzes list'),
    path('report/', AnalyzesReportView.as_view(), name='Analyzes report'),
    path('analyzes/<int:pk>/', AnalysisDetailView.as_view(), name='Analysis'),
    path('analyzes/<int:pk>/edit/', AnalyzesEditView.as_view(), name='Analysis edit'),
    path('analyzes/<int:pk>/history/', AnalysisHistoryView.as_view(), name='Analysis history'),
    path('tests/<int:pk>/edit/', TestEditView.as_view(), name='Test edit'),
    path('blanks/', BlanksListView.as_view(), name='Blanks list'),
    path('blanks/add/', BlankCreateView.as_view(), name='Create blank'),
    path('blanks/<slug>/', BlankDetailView.as_view(), name='Blank'),
    path('blanks/<slug>/edit/', BlankUpdateView.as_view(), name='Edit blank'),
    path('blanks/<slug>/delete/', BlankDeleteView.as_view(), name='Delete blank'),
    path('mapping/', AnalysisMappingListView.as_view(), name='Mapping_list'),
    path('mapping/upload/', AnalysisMappingUpload.as_view(), name='Upload_mapping'),
    path('mapping/<int:pk>/', AnalysisMappingHistoryView.as_view(), name='Mapping'),
    path('mapping/<int:pk>/edit/', AnalysisMappingEditView.as_view(), name='Mapping edit'),
]

lis_extender/bags/urls.py
from django.urls import path
from .views import LpuDetail, BagLPUDetail, BagLPUCreate, ScanBagView, AddBagtoLPU, BagsReportView, BagsLpuList, \
    LpuList, ScannedBagList, return_barcode, BagLPUUpdate, ScanBagDelete

urlpatterns = [
    path('bag_reg/', ScannedBagList.as_view(), name='scanbag_list'),
    path('bag_reg/add/', ScanBagView.as_view(), name='scan_bag'),
    path('bag_reg/<int:pk>/delete/', ScanBagDelete.as_view(), name='scanbag_delete'),
    path('lpu/', LpuList.as_view(), name='lpu_bags_list'),
    path('lpu/<int:pk>/', LpuDetail.as_view(), name='lpu'),
    path('lpu/<int:pk>/add_barcode/', AddBagtoLPU.as_view(), name='add_bag_to_lpu'),
    path('bag_lpu/', BagsLpuList.as_view(), name='bag_lpu_list'),
    path('bag_lpu/<int:pk>/', BagLPUDetail.as_view(), name='bag_lpu'),
    path('bag_lpu/<int:pk>/barcode.pdf', return_barcode, name='bag_lpu_barcode'),
    path('bag_lpu/add/', BagLPUCreate.as_view(), name='add_baglpu'),
    path('bag_lpu/<int:pk>/edit/', BagLPUUpdate.as_view(), name='bag_lpu_edit'),
    path('report/', BagsReportView.as_view(), name='bags_report'),
]

lis_extender/lis_extender/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('finance/', include('finance.urls')),
    path('bags/', include('bags.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('catalog/', include('analyzes.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lis_extender/analyzes/models.py
from django.db import models
from django.urls import reverse
from mainapp.models import LogEvent
import uuid


class TimeUnits(models.Model):
    name = models.CharField(max_length=5, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class MeasureUnit(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=50, unique=False)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class Analyzer(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('Analyzer', kwargs={'pk': self.id})


class Biomaterial(models.Model):
    id = models.IntegerField(primary_key=True)
    code = models.CharField(max_length=150, unique=True)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('Biomaterial', kwargs={'pk': self.id})

    class Meta:
        ordering = ('name',)


class Container(models.Model):
    id = models.IntegerField(primary_key=True)
    code = models.CharField(max_length=150, unique=True)
    name = models.CharField(max_length=255)
    short_name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('Container', kwargs={'pk': self.id})

    class Meta:
        ordering = ('name',)


class AnalysisGroup(models.Model):
    id = models.IntegerField(primary_key=True)
    code = models.CharField(max_length=150, unique=True)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('code',)


class Analysis(models.Model):
    id = models.IntegerField(primary_key=True)
    code = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=255)
    group = models.ForeignKey(
        to=AnalysisGroup,
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    link = models.URLField(blank=True, null=True)
    notes = models.TextField(default='')
    take_instructions = models.TextField(default='')
    store_conditions = models.TextField(default='')
    ready_for = models.CharField(max_length=10, blank=True, null=True)
    tags = models.TextField(default='')
    extra_appointment_days = models.IntegerField(blank=True, null=True)
    extra_appointment_units = models.ForeignKey(to=TimeUnits, on_delete=models.SET_NULL, blank=True, null=True,
                                                related_name='extra_appointment_units')
    stability_8 = models.IntegerField(blank=True, null=True)
    stability_8_unit = models.ForeignKey(to=TimeUnits, on_delete=models.SET_NULL, blank=True, null=True,
                                         related_name='stability_8_unit')
    stability_20 = models.IntegerField(blank=True, null=True)
    stability_20_unit = models.ForeignKey(to=TimeUnits, on_delete=models.SET_NULL, blank=True, null=True,
                                          related_name='stability_20_unit')
    analysis_method = models.TextField(default='Нет данных')
    reagent = models.FileField(upload_to='uploads/reagents/', blank=True, null=True, default=None)
    results_example = models.FileField(upload_to='uploads/results/', blank=True, null=True, default=None)
    clinical_meaning = models.TextField(default='Нет данных')
    influental_factors = models.TextField(default='Нет данных')
    get_ready = models.TextField(default='Нет данных')
    additional_biomaterials = models.ManyToManyField(to=Biomaterial)
    summary = models.TextField(default='')

    def __str__(self):
        return f'{self.code} {self.name}'

    def __eq__(self, other):
        if isinstance(other, Analysis):
            return (self.link == other.link and
                    self.notes == other.notes and
                    self.take_instructions == other.take_instructions and
                    self.store_conditions == other.store_conditions and
                    self.extra_appointment_days == other.extra_appointment_days and
                    self.extra_appointment_units == other.extra_appointment_units and
                    self.stability_8 == other.stability_8 and
                    self.stability_8_unit == other.stability_8_unit and
                    self.stability_20 == other.stability_20 and
                    self.stability_20_unit == other.stability_20_unit and
                    self.analysis_method == other.analysis_method and
                    self.clinical_meaning == other.clinical_meaning and
                    self.influental_factors == other.influental_factors and
                    self.additional_biomaterials.all() == other.additional_biomaterials.all()
                    )
        return NotImplemented

    def get_absolute_url(self):
        return reverse('Analysis', kwargs={'pk': self.id})

    def get_edit_url(self):
        return reverse('Analysis edit', kwargs={'pk': self.pk})

    def get_history_url(self):
        return reverse('Analysis history', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('group__name', 'code',)


class Blank(models.Model):
    code = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=255, default='')
    blank = models.FileField(upload_to='uploads/blanks/')
    slug = models.SlugField(default=uuid.uuid4, editable=False, unique=True)
    analyzes = models.ManyToManyField(to=Analysis)

    def __str__(self):
        return f'{self.code} {self.name}'

    def get_absolute_url(self):
        return reverse('Blank', kwargs={'slug': self.slug})

    def get_edit_url(self):
        return reverse('Edit blank', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('Delete blank', kwargs={'slug': self.slug})

    class Meta:
        ordering = ('code',)


class Test(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255, default='')
    short_name = models.CharField(max_length=255, default='')
    alternative_name = models.CharField(max_length=255, default='')
    measuring_units = models.ForeignKey(to=MeasureUnit, on_delete=models.SET_NULL, blank=True, null=True)
    references = models.TextField(default='Нет данных')
    is_technical = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('Test edit', kwargs={'pk': self.id})

    def get_edit_url(self):
        return reverse('Test edit', kwargs={'pk': self.id})

    class Meta:
        ordering = ('name',)


class AnalysisTests(models.Model):
    analysis = models.ForeignKey(to=Analysis, on_delete=models.CASCADE, related_name='tests')
    test = models.ForeignKey(to=Test, on_delete=models.CASCADE, related_name='test_analysis')


class BiomaterialSamplingGroup(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255)
    biomaterial = models.ForeignKey(to=Biomaterial, on_delete=models.CASCADE)
    container = models.ForeignKey(to=Container, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name


class AnalysisSamplingGroup(models.Model):
    analysis = models.ForeignKey(to=Analysis, on_delete=models.CASCADE)
    bsg = models.ForeignKey(to=BiomaterialSamplingGroup, on_delete=models.CASCADE)


class ProfileToSimple(models.Model):
    profile = models.ForeignKey(to=Analysis, on_delete=models.CASCADE, related_name='profile')
    simple_target = models.ForeignKey(to=Analysis, on_delete=models.CASCADE, related_name='simple')


class AnalysisAnalyzers(models.Model):
    analysis = models.ForeignKey(to=Analysis, on_delete=models.CASCADE)
    analyzer = models.ForeignKey(to=Analyzer, on_delete=models.CASCADE)


class AnalysisLog(models.Model):
    obj_instance = models.ForeignKey(to=Analysis, on_delete=models.CASCADE, related_name='analysis')
    event = models.ForeignKey(to=LogEvent, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-event__timestamp',)


class AnalysisMapping(models.Model):
    analysis = models.OneToOneField(to=Analysis, on_delete=models.CASCADE)
    cmd_code = models.CharField(max_length=20, default='', verbose_name='CMD')
    helix_code = models.CharField(max_length=20, default='', verbose_name='Helix')
    invitro_code = models.CharField(max_length=20, default='', verbose_name='InVitro')
    kdl_code = models.CharField(max_length=20, default='', verbose_name='KDL')
    gemotest_code = models.CharField(max_length=20, default='', verbose_name='Гемотест')
    dialab_code = models.CharField(max_length=20, default='', verbose_name='Диалаб')
    citilab_code = models.CharField(max_length=20, default='', verbose_name='Citilab')
    efis_code = models.CharField(max_length=20, default='', verbose_name='Эфис')
    unimed_code = models.CharField(max_length=20, default='', verbose_name='Юнимед')
    labquest_code = models.CharField(max_length=20, default='', verbose_name='LabQuest')
    summary = models.TextField(default='')

    def __str__(self):
        return f'{self.analysis}'

    def __eq__(self, other):
        if isinstance(other, AnalysisMapping):
            is_equal = True
            attrib_codes = [attrib for attrib in dir(other) if not callable(attrib) and 'code' in attrib]
            for attrib in attrib_codes:
                if getattr(self, attrib) != getattr(other, attrib):
                    is_equal = False
            return is_equal
        return NotImplemented

    def get_absolute_url(self):
        return reverse('Mapping', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('analysis__code',)


class AnalysisMappingLog(models.Model):

lis_extender/analyzes/templates/analyzes/analysis_edit.html
{% extends "analyzes/base_edit_form.html" %}

{% block title %}Редактировать {{object}} | {% endblock title %}


{% block header %}Редактировать {{object}}{% endblock header %}

lis_extender/analyzes/templates/analyzes/analysismapping_detail.html
{% extends "analyzes/base.html" %}

{% block title %}Сопоставление {{object}} | {% endblock title %}


{% block main %}
<div class="uk-content uk-margin-medium-top">
    <h4 class="uk-heading">{{ object }}</h4>
    <table class="uk-table uk-table-divider uk-table-middle">
        <thead class="uk-background-secondary">
        <tr>
            <th scope="col">Время изменения</th>
            <th scope="col">Кто изменил</th>
            <th scope="col">CMD</th>
            <th scope="col">Helix</th>
            <th scope="col">InVitro</th>
            <th scope="col">КДЛ</th>
            <th scope="col">Гемотест</th>
            <th scope="col">Диалаб</th>
            <th scope="col">Ситилаб</th>
            <th scope="col">Эфис</th>
            <th scope="col">Юнимед</th>
        </tr>
        </thead>
        <tbody id="list">
        {% for log_event in object.analysismappinglog.all %}
        <tr>
            <td>{{log_event.event.timestamp|date:'d.m.Y H:i'}}</td>
            {% with event_data=log_event.event.get_data %}
            <td>{{event_data.author}}</td>
            <td>{{event_data.cmd_code}}</td>
            <td>{{event_data.helix_code}}</td>
            <td>{{event_data.invitro_code}}</td>
            <td>{{event_data.kdl_code}}</td>
            <td>{{event_data.gemotest_code}}</td>
            <td>{{event_data.dialab_code}}</td>
            <td>{{event_data.citilab_code}}</td>
            <td>{{event_data.efis_code}}</td>
            <td>{{event_data.unimed_code}}</td>
            {% endwith %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock main %}

lis_extender/analyzes/templates/analyzes/analysismapping_list.html
{% extends "analyzes/base.html" %}

{% block title %}
Сопоставление каталогов |
{% endblock title %}

{% block main %}
<table class="uk-table uk-table-divider uk-table-middle uk-background-default">
    <thead class="uk-background-secondary">
    <tr>
        <th class="uk-table-shrink">Код</th>
        <th class="uk-table-expand">Название</th>
        <th class="uk-width-medium">CMD</th>
        <th class="uk-width-medium">Helix</th>
        <th class="uk-width-medium">InVitro</th>
        <th class="uk-width-medium">КДЛ</th>
        <th class="uk-width-medium">Гемотест</th>
        <th class="uk-width-medium">Диалаб</th>
        <th class="uk-width-medium">Ситилаб</th>
        <th class="uk-width-medium">Эфис</th>
        <th class="uk-width-medium">Юнимед</th>
        {% if perms.analyzes.change_analysismapping %}
        <th class="uk-table-shrink">
            <a href="{% url 'Upload_mapping' %}" class="uk-icon-button uk-icon button-nav" uk-icon="upload" title="Загрузить сопоставление"></a>
            Действия
        </th>
        {% endif %}
    </tr>
    </thead>
    <tbody id="list">
    {% for object in object_list %}
    <tr>
        <td>{{object.analysis.code}}</td>
        <td>{{object.analysis.name}}</td>
        <td>{{object.cmd_code}}</td>
        <td>{{object.helix_code}}</td>
        <td>{{object.invitro_code}}</td>
        <td>{{object.kdl_code}}</td>
        <td>{{object.gemotest_code}}</td>
        <td>{{object.dialab_code}}</td>
        <td>{{object.citilab_code}}</td>
        <td>{{object.efis_code}}</td>
        <td>{{object.unimed_code}}</td>
        {% if perms.analyzes.change_analysismapping %}
        <td>
            <div>
                <a class="uk-icon-button uk-icon button-nav" uk-icon="info"
                   href="{{object.get_absolute_url}}edit/"></a>
                {% if object.analysismappinglog.all %}
                <a class="uk-icon-button uk-icon button-nav" uk-icon="pencil"
                   href="{{object.get_absolute_url}}"></a>

                {% endif %}
            </div>
        </td>
        {% endif %}
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock main %}

lis_extender/analyzes/templates/analyzes/analyzer_detail.html
{% extends "analyzes/base_reversed_analysis.html" %}

{% block targets %}
{% for aa in object.analysisanalyzers_set.all %}
<tr class="analysis-row">
    <td>
        <a href="{{aa.analysis.get_absolute_url}}"
           class="uk-link-reset">{{aa.analysis}}</a>
    </td>
</tr>
{% empty %}
<tr>
    <td>Нет связанных исследований</td>
</tr>
{% endfor %}
{% endblock %}

lis_extender/analyzes/templates/analyzes/base_create_form.html
{% extends "mainapp/base_create_form.html" %}

{% block title %}Редактирование {{object}} | {% endblock title %}

{% block tabs %}
{% include "analyzes/tabs.html" %}
{% endblock tabs %}


{% block form_title %}Редактирование {{object}}{% endblock form_title %}

lis_extender/analyzes/templates/analyzes/base_edit_form.html
{% extends "mainapp/base_edit_form.html" %}

{% block title %}Редактирование {{object}} | {% endblock title %}

{% block tabs %}
{% include "analyzes/tabs.html" %}
{% endblock tabs %}

{% block form_title %}Редактирование {{object}}{% endblock form_title %}

lis_extender/analyzes/templates/analyzes/base_reversed_analysis.html
{% extends "analyzes/base.html" %}

{% block title %}Анализы, связанные с {{object}} | {% endblock title %}

{% block main %}
<div class="uk-container uk-margin-medium-top">
    <div class="uk-card uk-card-default">
        <div class="uk-card-header">
        <h3 class="uk-card-title">{{ object }}</h3>
    </div>
    <div class="uk-card-body">
    <table class="uk-table uk-table-divider uk-table-middle">
        <thead class="uk-background-secondary">
        <tr>
            <th scope="col">
                <div class="uk-grid-large uk-flex-middle uk-grid" uk-grid>
                    <div class="uk-width-expand uk-first-column">
                    Связанные исследования
                    </div>
                    <div class="uk-width-auto">
                        <form>
                            <fieldset class="uk-fieldset">
                                    <div class="uk-inline">
                                        <span class="uk-form-icon" uk-icon="icon: search"></span>
                                        <input type="text" class="uk-input" id="filten-input">
                                    </div>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </th>
        </tr>
        </thead>
        <tbody>
        {% block targets %}
        {% for same_analysis in object.group.analysis_set.all %}
        <tr class="analysis-row">
            <td><a href="{{same_analysis.get_absolute_url}}"
                   class="uk-link-reset">{{same_analysis}}</a></td>
        </tr>
        {% endfor %}
        {% endblock targets %}
        </tbody>
    </table>
    </div>
    </div>
</div>
{% endblock main %}

{% block scripts%}
<script>
filterElements('#filter-input', 'tbody');
</script>
{% endblock %}

lis_extender/analyzes/templates/analyzes/biomaterial_detail.html
{% extends "analyzes/base_reversed_analysis.html" %}

{% block targets %}
{% for bsg in object.biomaterialsamplinggroup_set.all %}
{% for asg in bsg.analysissamplinggroup_set.all %}
<tr class="analysis-row">
    <td>
        <a href="{{asg.analysis.get_absolute_url}}"
           class="uk-link-reset">{{asg.analysis}}</a>
    </td>
</tr>
{% endfor %}
{% endfor %}
{% endblock %}

lis_extender/analyzes/templates/analyzes/blank_detail.html
{% extends "analyzes/base_reversed_analysis.html" %}

{% block targets %}
{% for analysis in object.analyzes.all %}
<tr class="analysis-row">
    <td>
        <a href="{{analysis.get_absolute_url}}"
           class="uk-link-reset">{{analysis}}</a>
    </td>
</tr>
{% endfor %}
{% endblock %}

lis_extender/analyzes/templates/analyzes/blank_list.html
{% extends "analyzes/base.html" %}

{% block title %}
Бланки |
{% endblock title %}

{% block main %}
<div class="uk-flex uk-flex-center uk-margin uk-margin-medium-top">
    <form>
        <fieldset class="uk-fieldset">
            <div class="uk-inline">
                <span class="uk-form-icon" uk-icon="icon: search"></span>
                <input type="text" class="uk-input" id="filter-input">
            </div>
        </fieldset>
    </form>
</div>
<div class="uk-grid-small uk-child-width-expand@s uk-text-center" id="blanks" uk-grid>
    {% if perms.analyzes.add_blank %}
    <div class="uk-width-1-3">
        <div class="uk-card uk-card-default">
            <div class="uk-card-header">
                <h3 class="uk-card-title">Добавить бланк</h3>
            </div>
            <div class="uk-card-body">
                <div class="uk-margin uk-flex uk-flex-center">
                            <a href="{% url 'Create blank' %}" class="uk-icon-button uk-icon" uk-icon="icon: plus" title="Добавить" uk-toggle></a>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

    {% for object in object_list %}
    <div class="uk-width-1-3" id="row_{{ forloop.counter }}">
        <div class="uk-card uk-card-default">
            <div class="uk-card-header">
                <h3 class="uk-card-title">{{object.code}}</h3>
            </div>
            <div class="uk-card-body">
                <p>{{object.name}}</p>
                <div class="uk-margin uk-flex uk-flex-right">
                    <ul class="uk-grid-small uk-grid" uk-grid>
                        <li>
                            <a href="{{object.blank.url}}" class="uk-icon-button uk-icon" title="Скачать" target="_blank" uk-icon="icon: download"></a>
                        </li>
                        <li>
                            <a class="uk-icon-button uk-icon" uk-icon="icon: list" title="Исследования в бланке" href="{{object.get_absolute_url}}"></a>
                        </li>
                        {% if perms.analyzes.change_blank %}
                        <li>
                            <a class="uk-icon-button uk-icon" uk-icon="icon: pencil" title="Редактировать" href="{{object.get_edit_url}}"></a>
                        </li>
                        {% endif %}
                        {% if perms.analyzes.delete_blank %}
                        <li>
                                <a href="#modal_{{ object.pk }}" class="uk-icon-button uk-icon" uk-icon="icon: trash" title="Удалить" uk-toggle></a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
        <div id="modal_{{forloop.counter}}" uk-modal>
    <div class="uk-modal-dialog uk-modal-body">
        <h2 class="uk-modal-title">Удаление</h2>
        <p>Вы уверены, что хотите удалить <b>{{object}}?</b></p>
        <p class="uk-text-right">
            <button class="uk-button uk-button-default uk-modal-close" type="button">Отмена</button>
            <a href="{{ object.get_delete_url }}" class="uk-button uk-button-danger delete-button"
               type="button">Удалить</a>
        </p>
    </div>
</div>
        {% endfor %}
    </div>
</div>
{% csrf_token %}
{% endblock main %}


{% block scripts%}
<script>
filterElements('#filter-input', '#blanks');
</script>
{% endblock %}

lis_extender/analyzes/templates/analyzes/container_detail.html
{% extends "analyzes/base_reversed_analysis.html" %}

{% block targets %}
{% for bsg in object.biomaterialsamplinggroup_set.all %}
{% for asg in bsg.analysissamplinggroup_set.all %}
<tr class="analysis-row">
    <td>
        <a href="{{asg.analysis.get_absolute_url}}"
           class="uk-link-reset">{{asg.analysis}}</a>
    </td>
</tr>
{% endfor %}
{% empty %}
<tr>
    <td>Нет связанных исследований</td>
</tr>
{% endfor %}
{% endblock %}

lis_extender/analyzes/templates/analyzes/tabs.html
<div class="uk-container-expand">
    <div class="uk-margin-medium-top">
        <ul class="uk-flex-center uk-subnav uk-subnav-pill uk-subnav-divider">
          <li class="{% if '/catalog/analyzes/' in request.get_full_path %}uk-active{% endif %}">
            <a href="{% url 'Analyzes list' %}">Исследования</a>
          </li>
              {% if perms.analyzes.view_analysis %}
              <li class="{% if '/top100' in request.get_full_path %}uk-active{% endif %}">
                <a href="{% url 'Top100' %}">Топ 100 исследований</a>
              </li>
              {% endif %}
              {% if perms.analyzes.view_analysis %}
              <li class="{% if 'report/' in request.get_full_path %}uk-active{% endif %}">
                <a href="{% url 'Analyzes report' %}">Отчет по продажам</a>
              </li>
              {% endif %}
              {% if perms.analyzes.view_blank %}
              <li class="{% if '/catalog/blanks/' in request.get_full_path %}uk-active{% endif %}">
                <a href="{% url 'Blanks list' %}">Бланки</a>
              </li>
              {% endif %}
              {% if perms.analyzes.view_analysismapping %}
              <li class="{% if '/catalog/mapping/' in request.get_full_path %}uk-active{% endif %}">
                <a href="{% url 'Mapping_list' %}">Сопоставление каталогов</a>
              </li>
              {% endif %}
              {% if perms.analyzes.view_analyzer %}
              <li class="{% if '/catalog/analyzers/' in request.get_full_path %}uk-active{% endif %}">
                <a href="{% url 'Analyzers list' %}">Анализаторы</a>
              </li>
              {% endif %}
              {% if perms.analyzes.view_biomaterial %}
              <li class="{% if '/catalog/biomaterials/' in request.get_full_path %}uk-active{% endif %}">
                <a href="{% url 'Biomaterials list' %}">Биоматериалы</a>
              </li>
              {% endif %}
              {% if perms.analyzes.view_container %}
              <li class="{% if '/catalog/containers/' in request.get_full_path %}uk-active{% endif %}">
                <a href="{% url 'Container list' %}">Расходные материалы</a>
              </li>
              {% endif %}
         </ul>
    </div>
</div>

lis_extender/analyzes/templates/analyzes/test_edit.html
{% extends "analyzes/base_edit_form.html" %}

{% block title %}Редактировать {{object}} | {% endblock title %}


{% block header %}Редактировать {{object}}{% endblock header %}