lis_extender/bags/urls.py
from django.urls import path
from .views import LpuDetail, BagLPUDetail, BagLPUCreate, ScanBagView, AddBagtoLPU, BagsReportView, BagsLpuList, \
    LpuList, ScannedBagList, return_barcode, BagLPUUpdate, ScanBagDelete

urlpatterns = [
    path('bag_reg/', ScannedBagList.as_view(), name='scanbag_list'),
    path('bag_reg/add/', ScanBagView.as_view(), name='scan_bag'),
    path('bag_reg/<int:pk>/delete/', ScanBagDelete.as_view(), name='scanbag_delete'),
    path('lpu/', LpuList.as_view(), name='lpu_bags_list'),
    path('lpu/<int:pk>/', LpuDetail.as_view(), name='lpu'),
    path('lpu/<int:pk>/add_barcode/', AddBagtoLPU.as_view(), name='add_bag_to_lpu'),
    path('bag_lpu/', BagsLpuList.as_view(), name='bag_lpu_list'),
    path('bag_lpu/<int:pk>/', BagLPUDetail.as_view(), name='bag_lpu'),
    path('bag_lpu/<int:pk>/barcode.pdf', return_barcode, name='bag_lpu_barcode'),
    path('bag_lpu/add/', BagLPUCreate.as_view(), name='add_baglpu'),
    path('bag_lpu/<int:pk>/edit/', BagLPUUpdate.as_view(), name='bag_lpu_edit'),
    path('report/', BagsReportView.as_view(), name='bags_report'),
]

lis_extender/lis_extender/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('finance/', include('finance.urls')),
    path('bags/', include('bags.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('catalog/', include('analyzes.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lis_extender/mainapp/urls.py
from django.urls import path
from django.views.generic import ListView, DetailView, DeleteView
from .models import HSLink
from .views import CreateHE, UpdateHE, DeleteHE

urlpatterns = [
    path('', ListView.as_view(queryset=HSLink.objects.filter(is_active=True), template_name='mainapp/home.html'), name='home'),
    path('hl/', ListView.as_view(queryset=HSLink.objects.all()), name='home_elements'),
    path('hl/create/', CreateHE.as_view(), name='home_element_create'),
    path('hl/<slug>/', DetailView.as_view(model=HSLink), name='home_element_detail'),
    path('hl/<slug>/edit/', UpdateHE.as_view(), name='home_element_edit'),
    path('hl/<slug>/delete/', DeleteHE.as_view(), name='home_element_delete'),
    path('users/', ListView.as_view(), name='users'),
    path('users/create/', DetailView.as_view(), name='user_create'),
    path('users/<int:pk>/', DetailView.as_view(), name='user'),
    path('users/<int:pk>/edit/', DetailView.as_view(), name='user_edit'),
    path('users/<int:pk>/delete/', DeleteView.as_view(), name='user_delete'),
    path('positions/<int:pk>/', DetailView.as_view(), name='position'),
    path('positions/<int:pk>/edit/', DetailView.as_view(), name='position_edit'),
    path('positions/<int:pk>/delete/', DeleteView.as_view(), name='position_delete'),
]

lis_extender/bags/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from mainapp.models import LogEvent
from django.utils import timezone

DATETIME_INPUT_FORMATS = settings.DATETIME_INPUT_FORMATS


class LPU(models.Model):
    id = models.CharField(primary_key=True, max_length=100)
    code = models.CharField(max_length=20, unique=True)
    name = models.TextField()
    is_active = models.BooleanField()

    def __str__(self):
        return f'{self.code} {self.name}'

    def get_absolute_url(self):
        return reverse('lpu', kwargs={"pk": self.pk})

    def get_finance_url(self):
        return reverse('Customer details', kwargs={'pk': self.pk})

    def get_add_bag_url(self):
        return reverse('add_bag_to_lpu', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('code',)


class BagLPU(models.Model):
    barcode = models.IntegerField(unique=True)
    lpu = models.ForeignKey(to=LPU, on_delete=models.SET_NULL, blank=True, null=True, related_name='bag',
                            related_query_name='bags')
    create_date = models.DateTimeField(default=timezone.now)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, blank=True, null=True, default=None,
                                related_name='creator')

    def __str__(self):
        return f'ШК: {self.barcode} ЛПУ: {self.lpu}'

    def get_absolute_url(self):
        return reverse('bag_lpu', kwargs={'pk': self.pk})

    def get_edit_url(self):
        return reverse('bag_lpu_edit', kwargs={'pk': self.pk})

    def get_barcode_url(self):
        return reverse('bag_lpu_barcode', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('barcode',)


class ScannedBag(models.Model):
    barcode = models.IntegerField()
    scan_date = models.DateTimeField(default=timezone.now)
    lpu = models.ForeignKey(to=BagLPU, on_delete=models.CASCADE)
    incoming = models.BooleanField(default=True)
    creator = models.ForeignKey(to=User, on_delete=models.SET_NULL, blank=True, null=True, default=None)

    def __str__(self):
        formatted_scan_date = self.scan_date.strftime(DATETIME_INPUT_FORMATS[0])
        return f'{self.barcode} {formatted_scan_date} {self.lpu.lpu}'

    def get_absolute_url(self):
        return reverse('scanbag_delete', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('scanbag_delete', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('-scan_date',)


class PermissionReport(models.Model):
    name = models.CharField(max_length=2)


class BagLPULog(models.Model):
    obj_instance = models.ForeignKey(to=BagLPU, on_delete=models.CASCADE)
    event = models.ForeignKey(to=LogEvent, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-event__timestamp',)

lis_extender/finance/models.py
from django.db import models
from bags.models import LPU
from analyzes.models import Analysis


# Create your models here.
class FinancePerm(models.Model):
    class Meta:
        permissions = (
            ('cmd_bill_compare', 'Can compare cmd bill'),
            ('price_convert', 'Can convert prices'),
            ('view_own_sales_report', 'Can view report'),
            ('view_analysis_sales', 'Can view top 100 best selling analysis'),
            ('view_own_lpu_sales', 'Can view related lpus')
        )


class Sale(models.Model):
    id = models.IntegerField(primary_key=True)
    creation_date = models.DateTimeField()
    request_id = models.IntegerField()
    analysis = models.ForeignKey(to=Analysis, on_delete=models.CASCADE, related_name='sales')
    service_price = models.DecimalField(max_digits=9, decimal_places=2)
    lpu = models.ForeignKey(to=LPU, on_delete=models.CASCADE, related_name='lpu_sales')

lis_extender/mainapp/models.py
import json
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


class LogEvent(models.Model):
    timestamp = models.DateTimeField(default=timezone.now)
    data = models.TextField(default=str({}))

    def save_data(self, data):
        self.data = json.dumps(data)

    def get_data(self):
        return json.loads(self.data)

    class Meta:
        ordering = ('-timestamp',)


class HSLink(models.Model):
    name = models.CharField(max_length=120, verbose_name='Название')
    logo = models.ImageField(upload_to='uploads/home_logos/', verbose_name='Логотип', default='site.jpg')
    link = models.URLField(unique=True, verbose_name='Ссылка')
    description = models.TextField(verbose_name='Описание')
    slug = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    weight = models.IntegerField(default=1, verbose_name='Вес ссылки')
    is_active = models.BooleanField(default=True, verbose_name='Активна')
    create_date = models.DateTimeField(default=timezone.now)
    edit_date = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('home_element_detail', kwargs={'slug': self.slug})

    def get_edit_url(self):
        return reverse('home_element_edit', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('home_element_delete', kwargs={'slug': self.slug})

    class Meta:
        ordering = ('weight', 'name',)


class LaboratoryInfo(models.Model):
    name = models.CharField(max_length=50)
    short_name = models.CharField(max_length=50)
    logo = models.ImageField(null=True, blank=True, upload_to='logo/')


class Position(models.Model):
    name = models.CharField(max_length=120, unique=True)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    position = models.ForeignKey(to=Position, on_delete=models.SET_DEFAULT, null=True, blank=True, default=None)

lis_extender/mainapp/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import Http404, HttpResponse
from django.views.generic import FormView, UpdateView, DeleteView, ListView, CreateView
from django.db.transaction import atomic

from mainapp.models import LogEvent
from .forms import HSLinkUpdateForm, UserForm, ProfileForm, UserCreateForm, PositionForm
from .models import HSLink, Position
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import User


class AjaxDeleteView(DeleteView):

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return HttpResponse()

class CreateHE(PermissionRequiredMixin, CreateView):
    form_class = HSLinkUpdateForm
    template_name = 'mainapp/add_home_element.html'
    permission_required = 'mainapp.add_hslink'
    permission_denied_message = 'Для получения доступа обратитесь в IT отдел'

    def get_success_url(self):
        return reverse('home_elements')


class UpdateHE(PermissionRequiredMixin, UpdateView):
    model = HSLink
    form_class = HSLinkUpdateForm
    template_name = "mainapp/home_element_edit.html"
    queryset = HSLink.objects.all()
    permission_required = 'mainapp.change_hslink'
    permission_denied_message = 'Для получения доступа обратитесь в IT отдел'

    def get_success_url(self):
        return reverse('home_elements')

class DeleteHE(PermissionRequiredMixin, AjaxDeleteView):
    model = HSLink
    permission_required = 'mainapp.delete_hslink'
    permission_denied_message = 'Для получения доступа обратитесь в IT отдел'


class ChangeLogMixin:
    log_connector_class = None

    def make_log(self, attribs, original_object):
        log_data = {}
        for attrib in attribs:
            if getattr(self.object, attrib) == getattr(original_object, attrib):
                log_data[attrib] = 'Без изменений'
            else:
                value = getattr(original_object, attrib)
                log_data[attrib] = ' ' if value is None else str(value)
        if len(self.request.user.first_name) > 0 and len(self.request.user.last_name) > 0:
            username = self.request.user.get_full_name()
        else:
            username = str(self.request.user)
        log_data['author'] = username
        log_line = LogEvent()
        log_line.save_data(log_data)
        log_line.save()
        log_entry_connector = self.log_connector_class(obj_instance=self.object, event=log_line)
        log_entry_connector.save()


class FilteredListView(ListView):
    filterset_class = None

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
        return self.filterset.qs.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class UsersListView(PermissionRequiredMixin, FilteredListView):
    permission_required = 'auth.view_user'
    template_name = 'mainapp/credentials_list.html'
    queryset = User.objects.all()
    paginate_by = 15


class PositionsListView(PermissionRequiredMixin, FilteredListView):
    permission_required = 'auth.view_user'
    template_name = 'mainapp/credentials_list.html'
    queryset = Position.objects.all()
    paginate_by = 15


class UserCreateView(PermissionRequiredMixin, FormView):
    permission_required = 'auth.add_user'
    template_name = 'mainapp/user_create.html'
    form_class = UserCreateForm

    def form_valid(self, form):
        user_data = form.cleaned_data
        del user_data['password_confirmation']
        groups = user_data.pop('groups')
        position = user_data.pop('position')
        user = User.objects.create_user(**user_data)
        user.is_active = True
        for group in groups:
            user.groups.add(group)
        user.save()
        user.profile.position = position
        user.profile.save()


@permission_required(perm='auth.change_user')
@atomic
def update_user(request, pk):
    try:
        user = get_object_or_404(User, pk=pk)
    except User.DoesNotExist:
        raise Http404()
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=user)
        profile_form = ProfileForm(request.POST, instance=user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            profile_form.save()
            user_form.save()
            if request.GET.get('next') is not None:
                success_url = request.GET.get('next')
            else:
                success_url = reverse('customers')
            return redirect(success_url)
    else:
        user_form = UserForm(instance=user)
        profile_form = ProfileForm(instance=user.profile)
    return render(request, 'mainsapp/customer_form.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })


class PositionCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'mainapp.add_position'
    model = Position
    form_class = PositionForm


class PositionEditView(PermissionRequiredMixin, UpdateView):
    permission_required = 'mainapp.change_position'
    model = Position
    form_class = PositionForm

lis_extender/mainapp/templates/mainapp/add_home_element.html
{% extends "mainapp/base_create_form.html" %}

{% block title %}
Добавить ресурс на главную |
{% endblock title%}


{% block form_title %}
Добавить ресурс на главную
{% endblock form_title %}

lis_extender/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial_scale=1.0" ]>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
        {% endblock title%}
        Лабораторный портал
    </title>

    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <link rel="stylesheet" href="{% static 'css/uikit.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/tail.select-default.css' %}">

    <link rel="stylesheet" href="{% static 'css/the-datepicker.css' %}">

    <link rel="stylesheet" href="{% static 'css/portal.css' %}">


</head>
<body>
<main>
    {% if user.is_authenticated %}
    {% include "mainapp/navbar.html" %}
    {% endif %}
    <div uk-height-viewport class="uk-section-default">

        {% block tabs %}
        {% endblock tabs %}

        {% if filterset.form %}
        {% include 'mainapp/filter.html' %}
        {% endif %}
        <div class="uk-container uk-container-large">
            {% block main %}
            {% endblock main %}

            {% if is_paginated %}
            {% include "mainapp/paginator.html" %}
            {% endif %}
        </div>
    </div>
</main>

</body>

<script src="{% static 'js/uikit.min.js' %}"></script>
<script src="{% static 'js/uikit-icons.min.js' %}"></script>
<script src="{% static 'js/tail.select.min.js' %}"></script>
<script src="{% static 'js/tail.select-ru.js' %}"></script>
<script src="{% static 'js/the-datepicker.min.js' %}"></script>
<script src="{% static 'js/miscellaneous.js' %}"></script>

{% block scripts%}
{% endblock scripts %}

{% if messages %}
<script>
const frontMessages = {}
    {% for message in messages %}

    let messageLevel;
    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
    messageLevel = 'success'
    {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
    messageLevel = 'danger'
    {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
    messageLevel = ''
    {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
    messageLevel = 'warning'
    {% endif %}
    frontMessages['{{ message|escapejs }}'] = messageLevel
    {% endfor %}

document.addEventListener('DOMContentLoaded', messageIterator(frontMessages));



</script>
{% endif %}

</html>

lis_extender/mainapp/templates/mainapp/base_create_form.html
{% extends 'mainapp/form_wrapper.html' %}

{% block title %}
{% endblock title %}

{% block tabs %}
{% endblock tabs %}

{% block form_title %}
{% endblock form_title %}


{% block button_name %}Добавить{% endblock button_name %}

lis_extender/mainapp/templates/mainapp/base_edit_form.html
{% extends 'mainapp/form_wrapper.html' %}

{% block title %}
{% endblock title %}

{% block tabs %}
{% endblock tabs %}

{% block form_title %}
{% endblock form_title %}


{% block button_name %}Сохранить{% endblock button_name %}

lis_extender/mainapp/templates/mainapp/filter.html
<div class="uk-container-expand">
    <div class="uk-flex uk-flex-center">
        <form method="get" class="uk-grid-small uk-flex-middle uk-grid" uk-grid>
            {% for field in filterset.form %}
                {% if field.field.widget.input_type == 'checkbox' %}
                <div class="uk-margin-top uk-margin-bottom">
                    <label>{{ field }} {{ field.label }}</label>
                </div>
                {% elif field.field.widget.input_type == 'select' %}
                <div class="uk-margin-top uk-margin-bottom">
                    <label class="uk-form-label" for="id_{{ field.name }}">{{ field.label }}</label>
                    <div class="uk-form-controls">
                        {{ field }}
                    </div>
                </div>
                {% else %}
                <div class="uk-margin-top uk-margin-bottom">
                    <label class="uk-form-label" for="id_{{ field.name }}">{{ field.label }}</label>
                    <div class="uk-form-controls">
                    {{ field }}
                    </div>
                    {% for error in field.errors %}
                    <span class="helper-text red-text">{{ error|escape }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            {% endfor %}
            <div class="uk-margin-top">
            <button class="uk-icon-button uk-icon button-primary" type="submit" uk-icon="icon: search">
            </button>
            </div>

        </form>
    </div>
</div>

lis_extender/mainapp/templates/mainapp/home.html
{% extends 'mainapp/base.html' %}


{% block main %}
<div class="container">
    <div class="uk-grid-large uk-flex-middle uk-grid" uk-grid>
        <div class="uk-width-expand uk-first-column">
            <h1 class="uk-heading-small uk-heading-divider">Полезные ресурсы</h1>
        </div>
        <div class="uk-width-auto">
            <ul class="uk-iconnav">
            {% if perms.mainapp.add_hslink %}
                <li><a href="{% url 'home_element_create' %}" uk-icon="icon: plus" title="Добавить"></a></li>
            {% endif %}
            {% if perms.mainapp.view_hslink %}
                <li><a href="{% url 'home_elements' %}" uk-icon="icon: list" title="Список"></a></li>
            {% endif %}
            </ul>
        </div>
    </div>
</div>
<div class="uk-grid-large uk-child-width-expand@s uk-text-center uk-grid uk-margin-medium-top" uk-grid>
    {% for home_element in object_list %}
    <div class="uk-width-1-3">
        <div class="uk-card uk-card-default ">
            <div class="uk-card-media-top">
                <a target="_blank" href="{{ home_element.link }}">
                    <img src="{{ home_element.logo.url }}" alt="Resource logo">
                </a>
            </div>
            <div class="uk-card-body">
                <h3 class="uk-card-title">{{home_element.name}}</h3>
                <p>{{home_element.description}}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock main %}

lis_extender/mainapp/templates/mainapp/home_element_edit.html
{% extends "mainapp/base_edit_form.html" %}

{% block title %}
Редактировать ресурс {{object.name}} |
{% endblock title%}


{% block form_title %}
Редактировать ресурс {{object.name}}
{% endblock form_title %}

lis_extender/mainapp/templates/mainapp/navbar.html
<nav class="uk-navbar-container uk-margin" uk-navbar>
    <div class="uk-navbar-left">
    <a class="uk-navbar-item uk-logo" href="/">Лабораторный портал</a>
        <ul class="uk-navbar-nav">
            {% if perms.analyzes.view_analysis %}
            <li class="{% if 'catalog/' in request.path %} uk-active {% endif %}">
                <a href="{% url 'Analyzes list' %}">Каталог анализов</a>
                <div class="uk-navbar-dropdown">
                    <ul class="uk-nav uk-navbar-dropdown-nav">
                        {% if perms.analyzes.view_analyzer %}
                        <li class="{% if 'analyzers/' in request.path %} uk-active {% endif %}">
                            <a href="{% url 'Analyzers list' %}">Анализаторы</a>
                        </li>
                        {% endif %}
                        {% if perms.analyzes.view_biomaterial %}
                        <li class="{% if 'biomaterials/' in request.path %} uk-active {% endif %}">
                            <a href="{% url 'Biomaterials list' %}">Биоматериалы</a>
                        </li>
                        {% endif %}
                        {% if perms.analyzes.view_container %}
                        <li class="{% if 'containers/' in request.path %} uk-active {% endif %}">
                            <a href="{% url 'Container list' %}">Контейнеры</a>
                        </li>
                        {% endif %}
                        {% if perms.analyzes.view_blank %}
                        <li class="{% if 'blanks/' in request.path and not 'add/' in request.path %} uk-active {% endif %}">
                            <a href="{% url 'Blanks list' %}">Бланки</a>
                        </li>
                        {% endif %}
                        {% if perms.analyzes.add_blank %}
                        <li class="{% if 'blanks/add/' in request.path %} uk-active {% endif %}">
                            <a href="{% url 'Create blank' %}">Добавить бланк</a>
                        </li>
                        {% endif %}
                        {% if perms.analyzes.view_analysismapping %}
                        <li class="{% if '/catalog/mapping/' in request.path and not 'upload/' in request.path %} uk-active {% endif %}">
                            <a href="{% url 'Mapping_list' %}">Сопоставление каталогов</a>
                        </li>
                        {% endif %}
                        {% if perms.analyzes.change_analysismapping %}
                        <li class="{% if 'mapping/upload/' in request.path %} uk-active {% endif %}">
                            <a href="{% url 'Upload_mapping' %}">Загрузить сопоставление</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </li>
            {% endif %}
            {% if perms.bags.view_lpu or perms.bags.view_scannedbag or perms.bags.view_baglpu or perms.bags.view_scannedbag or perms.bags.view_permissionreport %}
            <li class="{% if 'bags/' in request.path %} uk-active {% endif %}">
                <a href="{% url 'scanbag_list' %}">
                    Учет термоконтейнеров
                </a>
                <div class="uk-navbar-dropdown">
                    <ul class="uk-nav uk-navbar-dropdown-nav">
                        {% if perms.bags.add_scannedbag %}
                        <li class="{% if 'bag_reg/add/' in request.path %} uk-active {% endif %}">
                            <a href="{% url 'scan_bag' %}">Сканировать контейнеры</a>
                        </li>
                            {% endif %}
                        {% if perms.bags.add_baglpu %}
                        <li class="{% if 'bag_lpu/add/' in request.path %} uk-active {% endif %}">
                            <a href="{% url 'add_baglpu' %}">Выдать контейнер ЛПУ</a>
                        </li>
                        {% endif %}
                        {% if perms.bags.view_baglpu %}
                        <li class="{% if 'bag_lpu/' in request.path %} uk-active {% endif %}">
                            <a href="{% url 'bag_lpu_list' %}">Контейнеры</a>
                        </li>
                        {% endif %}
                        {% if perms.bags.view_lpu %}
                        <li class="{% if '/bags/lpu/' in request.path %} uk-active {% endif %}">
                            <a href="{% url 'lpu_bags_list' %}">ЛПУ</a>
                        </li>
                        {% endif %}
                        {% if perms.bags.view_permissionreport %}
                        <li class="{% if 'bags/report/' in request.path %} uk-active {% endif %}">
                            <a href="{% url 'bags_report' %}">Отчет</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </li>
            {% endif %}
            {% if perms.finance.price_convert or perms.finance.cmd_bill_compare or perms.finance.view_sale%}
            <li class="{% if 'finance/' in request.path %} uk-active {% endif %}">
                <a  href="#">
                    Финансы
                </a>
                <div class="uk-navbar-dropdown uk-navbar-dropdown-width-2">
                    <div class="uk-navbar-dropdown-grid uk-child-width-1-2" uk-grid>
                        <ul class="uk-nav uk-navbar-dropdown-nav">
                            {% if perms.bags.view_lpu and perms.finance.price_convert or perms.finance.view_sale%}
                            <li class="{% if 'customers/' in request.path %} uk-active {% endif %}">
                                <a href="{% url 'Customers' %}">Заказчики</a>
                            </li>
                            {% endif %}
                            {% if perms.bags.view_lpu and perms.finance.view_sale %}
                            <li class="{% if 'sales_report/' in request.path %} uk-active {% endif %}">
                                <a href="{% url 'Sales report' %}">Отчет по продажам</a>
                            </li>
                            {% endif %}
                            {% if perms.finance.price_convert %}
                            <li class="{% if 'price_converter/' in request.path %} uk-active {% endif %}">
                                <a href="{% url 'price_converter' %}">Конвертация прайс-листа для ЛИС</a>
                            </li>
                            <li class="{% if 'external_price_converter/' in request.path %} uk-active {% endif %}">
                                <a href="{% url 'ext_price_converter' %}">Конвертация прайс-листа сторонней лаборатории</a>
                            </li>
                            {% endif %}
                            {% if perms.finance.cmd_bill_compare %}
                            <li class="{% if 'cmd_bill_compare/' in request.path %} uk-active {% endif %}">
                                <a href="{% url 'bill_compare' %}">Сверка счета из CMD</a>
                            </li>
                        {% endif %}
                        </ul>
                </div>
            </li>
            {% endif %}
        </ul>
    </div>
    <div class="uk-navbar-right">
        <ul class="uk-navbar-nav">
            <li>
                <a href="#">{{user.first_name}} {{ user.last_name }}</a>
            </li>
            <li>
                <a title="Выйти" uk-icon="push" href="/account/logout/"></a>
            </li>
        </ul>
    </div>
</nav>